services:
  phoenix:
    image: arizephoenix/phoenix:${PHOENIX_VERSION}
    container_name: phoenix
    ports:
      - "${PHOENIX_PORT}:6006"
    restart: always
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
      - ${PHOENIX_WORKING_DIR}:/mnt/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6006 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${POSTGRES_PORT}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3


# --- Uncomment for local development --- #
# volumes:
#   database_data:
#     driver: local
